name: Estudo

on:
  push:
    branches: ["CI"]

permissions:
  contents: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t $(date +%s) .

  test:
    needs: build
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install pytest Flask-Testing SQLAlchemy flask_sqlalchemy flask_login flask_bcrypt flask_wtf
      - name: Run tests
        run: PYTHONPATH=$PYTHONPATH:. pytest

  bandit:
    needs: test
    name: Bandit 
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Bandit Analysis
        uses: PyCQA/bandit-action@v1