name: Estudo

on:
  push:
    branches: ["CI"]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t task-image .

  test:
    needs: build
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        run: PYTHONPATH=$PYTHONPATH:. pytest

  bandit:
    needs: test
    name: Análise de Segurança com Bandit
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Bandit Analysis
        uses: PyCQA/bandit-action@v1

  dependency_check:
    needs: test
    name: Análise de Dependências
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Create reports directory
        run: mkdir -p reports
      - name: Check dependencies
        uses: dependency-check/Dependency-Check_Action@main
        id: Dependency-Check
        with:
          project: "Task-Manager-using-Flask"
          path: "."
          format: "HTML"
          out: "reports"
          args: >
            --scan ./*.py
            --scan requirements.txt
            --failOnCVSS 7
            --enableRetired
      - name: Upload Dependency Check results
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check report
          path: reports

  security_analysis:
    needs: bandit
    name: Análise de Segurança Adicional
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Create reports directory
        run: mkdir -p reports
      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Dependency-Check
        with:
          project: "Task-Manager-using-Flask"
          path: "."
          format: "HTML"
          out: "reports"
          args: >
            --scan ./*.py
            --scan requirements.txt
            --failOnCVSS 7
            --enableRetired
      - name: Upload Security Analysis results
        uses: actions/upload-artifact@v4
        with:
          name: Security Analysis report
          path: reports

  codeql_analysis:
    needs: [test, bandit, dependency_check]
    name: Análise de Código com CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: github/codeql-action/setup@v2
        with:
          languages: python
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  deploy:
    needs: [codeql_analysis, security_analysis]
    name: Simulação de Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: pull automatic
          target_branch: revisao
          assignee: ${{ github.actor }}
          label: automatic
          get_diff: true