name: Estudo

on:
  push:
    branches: ["CI"]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t task-image .

  test:
    needs: build
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install pytest Flask-Testing SQLAlchemy flask_sqlalchemy flask_login flask_bcrypt flask_wtf
      - name: Run tests
        run: PYTHONPATH=$PYTHONPATH:. pytest

  bandit:
    needs: test
    name: Bandit 
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Bandit Analysis
        uses: PyCQA/bandit-action@v1

  dependency_check:
    needs: test
    name: Análises Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Create reports directory
        run: mkdir -p reports
      - name: Check dependency
        uses: dependency-check/Dependency-Check_Action@main
        id: Dependency-Check
        with:
          project: "Task-Manager-using-Flask"
          path: "."
          format: "HTML"
          out: "reports"
          args: >
            --scan ./*.py
            --scan requirements.txt
            --failOnCVSS 7
            --enableRetired
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check report
          path: ${{github.workspace}}/reports

  zap:
    needs: 
      - bandit
      - dependency_check
    name: Relatório ZAP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t task-image .
      - name: Run application
        run: |
          docker run -d -p 5000:5000 --name task-manager task-image
          sleep 30  # Aumentar tempo de espera para garantir que a aplicação está pronta
      - name: Zap Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://localhost:5000"
          issue: false  # Desativar a criação automática de issues.
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Scan Report
          path: report_html.html  # Ou o caminho onde o relatório do ZAP foi salvo...

  pull_request:
    needs: zap
    name: Simulação de Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: pull automatic
          target_branch: revisao
          assignee: ${{ github.actor }}
          label: automatic
          get_diff: true